# Generated by Django 4.1.2 on 2022-10-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creationTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
