# Generated by Django 4.1.2 on 2022-10-28 21:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('audio', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_set', to='albums.album')),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
