# Generated by Django 4.1.2 on 2022-10-28 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_songform_delete_song'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SongForm',
            new_name='Song',
        ),
    ]
